apiVersion: apps/v1
kind: Deployment
metadata:
  name: Contract
  labels:
    app: Contract
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Contract
  template:
    metadata:
      labels:
        app: Contract
    spec:
      containers:
        - name: Contract
          image: carrentaltest1.azurecr.io/test-contract:v3
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5