apiVersion: apps/v1
kind: Deployment
metadata:
  name: contract
  labels:
    app: contract
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contract
  template:
    metadata:
      labels:
        app: contract
    spec:
      containers:
        - name: contract
          image: carrentaltest.azurecr.io/contract:latest
          ports:
            - containerPort: 8080
#          resources:
#            limits:
#              cpu: 500m
#            requests:
#              cpu: 200m
          ## Config map Set start
		  env:
		    - name: SYSTEM_MODE
		    valueFrom:
		      configMapKeyRef:
                name: systemmode
                key: sysmodeval
          ## Config map Set end
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
